name: ibm周五部署
on:
  schedule:
    - cron: 35 21 * * 4
  watch:
    types: started       
jobs:
  build:
    runs-on: ubuntu-20.04  
    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y install wget
        sudo apt-get -y install unzip
    - name: down cf
      run: |
        curl -LO https://s3-us-west-1.amazonaws.com/cf-cli-releases/releases/v6.53.0/cf-cli_6.53.0_linux_x86-64.tgz
        tar zxvf cf-cli_6.53.0_linux_x86-64.tgz
        sudo mv ./cf /usr/bin/cf
        rm -rf ./cf-cli_6.53.0_linux_x86-64.tgz
        rm -rf ./LICENSE
        rm -rf ./NOTICE
        rm -rf ./README.md
        chmod +x ./go
    - name: cf login
      run: |
        cf api api.us-south.cf.cloud.ibm.com
        cf login -u ${{ secrets.ibmuser }} -p ${{ secrets.ibmpassword }}
    - name: cf push ibmyuming 
      run: |
        wget https://raw.githubusercontent.com/gossh520/cdcs/main/manifest.yml
        sed -i "s/yuming/${{ secrets.ibmyuming }}/g" ./manifest.yml
        ls
        cf push
        rm -rf manifest.yml
    - name: cf push ibmyuming1
      run: |
        wget https://raw.githubusercontent.com/gossh520/cdcs/main/manifest.yml
        sed -i "s/yuming/${{ secrets.ibmyuming1 }}/g" ./manifest.yml
        cf push
        rm -rf manifest.yml
        env
    - name: cf logout
      run: |
        ls
        cf logout      
        
