name: ibm周五部署
on:
  schedule:
    - cron: 35 21 * * 4
  watch:
    types: started       
jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v1
    - name: Install build dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y install wget
        sudo apt-get -y install unzip
    - name: down cf
      run: |
        curl -LO https://s3-us-west-1.amazonaws.com/cf-cli-releases/releases/v6.53.0/cf-cli_6.53.0_linux_x86-64.tgz
        tar zxvf cf-cli_6.53.0_linux_x86-64.tgz
        sudo mv ./cf /usr/bin/cf
        rm -rf ./cf-cli_6.53.0_linux_x86-64.tgz
        rm -rf ./LICENSE
        rm -rf ./NOTICE
    - name: down v2ray
      run: |
        curl -LO https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-arm64-v8a.zip
        unzip v2ray-linux-arm64-v8a.zip
        rm -rf ./v2ray
        rm -rf ./v2ray-linux-arm64-v8a.zip
        rm -rf ./systemd
        rm -rf ./config.json
        rm -rf ./v2ctl
        rm -rf ./geosite.dat
        rm -rf ./vpoint_socks_vmess.json
        rm -rf ./vpoint_vmess_freedom.json
        rm -rf ./README.md
    - name: cf login
      run: |
        cf api api.us-south.cf.cloud.ibm.com
        cf login -u ${{ secrets.ibmuser }} -p ${{ secrets.ibmpassword }}
    - name: cf push ibmyuming 
      run: |
        wget http://www.armn1.ml/kk/manifest.yml
        sed -i "s/yuming/${{ secrets.ibmyuming }}/g" ./manifest.yml
        wget http://www.armn1.ml/kk/webkk
        chmod +x ./webkk
        ls
        cf push
        rm -rf manifest.yml
        rm -rf webkk
    - name: cf push ibmyuming1
      run: |
        wget http://www.armn1.ml/kk/manifest.yml
        sed -i "s/yuming/${{ secrets.ibmyuming1 }}/g" ./manifest.yml
        wget http://www.armn1.ml/kk/webkk
        chmod +x ./webkk
        cf push
        rm -rf manifest.yml
        rm -rf webkk   
    - name: cf logout
      run: |
        ls
        cf logout      
        
