name: ibmssv2
on:
  #schedule:
    #- cron: 10 22 * * *
  watch:
    types: started       
jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v1
    - name: Install build dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y install wget
        sudo apt-get -y install curl
    - name: down cf
      run: |
        curl -LO https://s3-us-west-1.amazonaws.com/cf-cli-releases/releases/v6.53.0/cf-cli_6.53.0_linux_x86-64.tgz
        tar zxvf cf-cli_6.53.0_linux_x86-64.tgz
        sudo mv ./cf /usr/bin/cf
    - name: cf login
      run: |
        cf api api.us-south.cf.cloud.ibm.com
        cf login -u ${{ secrets.ibmuser }} -p ${{ secrets.ibmpassword }}
    - name: cf push
      run: |
        sed -i "s/yuming/${{ secrets.ibmyuming }}/g" ./manifest.yml
        cf push
    - name: cf logout
      run: |
        cf logout      
        
