name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Installation depends
        run:  |
          sudo apt-get update
          sudo apt-get -y install libjson-perl patchutils lzop build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync
      # Runs a set of commands using the runners shell
      - name: Clone source code && Build
        run: |
          git clone https://github.com/RuralHunter/CoreELEC
          cd CoreELEC
          ./mkn1
      - name : Upload artifact 
        uses: actions/upload-artifact@master
        with: 
          name: CoreELEC
          path: CoreELEC/build.CoreELEC-Phicomm-N1.arm-9.2.5
